# Generated by Django 5.2.5 on 2025-11-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morsecode_reader_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='address',
            field=models.TextField(blank=True, default='no address added', null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
