# Generated by Django 5.2.8 on 2025-11-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morsecode_reader_app', '0002_register_address_register_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
