# Generated by Django 5.2.5 on 2025-11-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morsecode_reader_app', '0004_admin_register'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='username',
            new_name='user',
        ),
    ]
