# Generated by Django 5.2.5 on 2025-11-26 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morsecode_reader_app', '0005_rename_username_register_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin_register',
            name='name',
        ),
    ]
