# Generated by Django 5.2.8 on 2025-11-27 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morsecode_reader_app', '0006_remove_admin_register_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin_register',
            old_name='username',
            new_name='fullname',
        ),
    ]
