# Generated by Django 5.2.8 on 2025-11-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morsecode_reader_app', '0007_rename_username_admin_register_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_register',
            name='username',
            field=models.TextField(blank=True, default='no user name added', null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.TextField(blank=True, default='no user name added', null=True),
        ),
    ]
