# Generated by Django 5.2.8 on 2025-11-27 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morsecode_reader_app', '0008_admin_register_username_register_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='name',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='register',
            name='user',
        ),
    ]
