# Generated by Django 5.2.8 on 2025-11-27 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morsecode_reader_app', '0009_rename_name_register_fullname_remove_register_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_Register',
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
