# Generated by Django 5.2.5 on 2025-12-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morsecode_reader_app', '0014_guardian_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='health_condition',
            field=models.CharField(blank=True, choices=[('paraplegia', 'Paraplegia'), ('quadriplegia', 'Quadriplegia'), ('hemiplegia', 'Hemiplegia'), ('partial', 'Partial Paralysis'), ('temporary', 'Temporary Paralysis'), ('other', 'Other')], max_length=30, null=True),
        ),
    ]
