# Generated by Django 5.2.5 on 2025-12-31 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morsecode_reader_app', '0015_register_health_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
