# Generated by Django 5.2.5 on 2026-01-01 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morsecode_reader_app', '0016_register_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian_register',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
