# Generated by Django 5.2.5 on 2026-01-01 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morsecode_reader_app', '0017_guardian_register_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardianAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morsecode_reader_app.guardian_register')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='morsecode_reader_app.register')),
            ],
        ),
    ]
