# Generated by Django 5.2.8 on 2026-01-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morsecode_reader_app', '0018_guardianaccessrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianaccessrequest',
            name='child_dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guardianaccessrequest',
            name='child_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='guardianaccessrequest',
            name='relation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
