# Generated by Django 5.2.8 on 2026-01-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morsecode_reader_app', '0019_guardianaccessrequest_child_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianaccessrequest',
            name='child_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guardianaccessrequest',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='guardian_proofs/'),
        ),
        migrations.AddField(
            model_name='guardianaccessrequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
