# Generated by Django 5.2.8 on 2026-01-30 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morsecode_reader_app', '0020_guardianaccessrequest_child_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blink_sensitivity', models.FloatField(default=0.22)),
                ('dot_time', models.IntegerField(default=600)),
                ('pause_time', models.IntegerField(default=2000)),
                ('head_movement', models.BooleanField(default=False)),
                ('facial_mouse', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='morsecode_reader_app.register')),
            ],
        ),
    ]
