# Generated by Django 5.2.10 on 2026-02-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morsecode_reader_app', '0021_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianaccessrequest',
            name='child_email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
