# Generated by Django 5.2.5 on 2026-02-10 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morsecode_reader_app', '0023_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
