# Generated by Django 5.2.8 on 2026-02-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morsecode_reader_app', '0024_delete_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='dot_time',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='debounce_time',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='enable_eye',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='enable_sos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='extra_long_blink_time',
            field=models.IntegerField(default=2000),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='long_blink_time',
            field=models.IntegerField(default=1200),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='medium_blink_time',
            field=models.IntegerField(default=700),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='short_blink_time',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='pause_time',
            field=models.IntegerField(default=1500),
        ),
    ]
