# Generated by Django 5.2.5 on 2026-02-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morsecode_reader_app', '0025_remove_usersettings_dot_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='word_gap_time',
            field=models.IntegerField(default=2500),
        ),
    ]
