# Generated by Django 5.2.8 on 2026-02-19 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morsecode_reader_app', '0026_usersettings_word_gap_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='debounce_time',
        ),
    ]
