# Generated by Django 5.2.8 on 2026-02-19 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morsecode_reader_app', '0027_remove_usersettings_debounce_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='extra_long_blink_time',
            field=models.IntegerField(default=2500),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='long_blink_time',
            field=models.IntegerField(default=1500),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='pause_time',
            field=models.IntegerField(default=1700),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='word_gap_time',
            field=models.IntegerField(default=3000),
        ),
    ]
