# Generated by Django 5.2.8 on 2026-02-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morsecode_reader_app', '0028_alter_usersettings_extra_long_blink_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='head_movement',
        ),
    ]
