# Generated by Django 5.2.8 on 2026-02-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morsecode_reader_app', '0029_remove_usersettings_head_movement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='extra_long_blink_time',
            field=models.IntegerField(default=2000),
        ),
    ]
