# Generated by Django 5.2.8 on 2026-02-20 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morsecode_reader_app', '0030_alter_usersettings_extra_long_blink_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin_Register',
        ),
    ]
