# Generated by Django 5.2.8 on 2026-02-20 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('morsecode_reader_app', '0032_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHighScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('high_score', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_score', to='morsecode_reader_app.register')),
            ],
        ),
    ]
