# Generated by Django 5.2.8 on 2026-02-22 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('morsecode_reader_app', '0035_passwordresetotp_guardian_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='status',
        ),
    ]
